trigger:
- test-azure

jobs:
# Linux
- job: Linux
  variables:
    VCPKG_ROOT: '$(Agent.HomeDirectory)/vcpkg'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: |
      sudo apt-get update
      sudo apt-get install ninja-build libudev-dev
    displayName: 'Install toolchain'
  - bash: |
      git clone https://github.com/NordicPlayground/vcpkg.git $(VCPKG_ROOT)
      $(VCPKG_ROOT)/bootstrap-vcpkg.sh
    displayName: 'Install vcpkg'
  - bash: |
      export PATH=$VCPKG_ROOT:$PATH
      vcpkg install nrf-ble-driver:x64-linux
    displayName: 'Install nrf-ble-driver'
  - template: azure-node.yml  # Template reference
    parameters:
      nodeVersion: 8.15.0
  - template: azure-node.yml  # Template reference
    parameters:
      nodeVersion: 8.15.0
      npm_config_runtime: 'electron'
      npm_config_target: 2.0.17
      npm_config_disturl: 'https://atom.io/download/electron'
